# ----------------- RAG Config -----------------

# Models
llm_model: gpt-4o-mini
embedding_model: text-embedding-3-small

# Retrieval
chunk_size: 500
chunk_overlap: 50
top_k: 5

# Paths
upload_folder: documents/
faiss_index: vectorstore/index.faiss
